/**
 * Created by Ann Marie on 7/6/2014.
 */
/* Hi Lo Game.  Guess a number between 1 -100. Random number generated by computer. Computer play against self with max 1000 guesses */

//computer to come up with random number between 1 - 100
function mysteryNum() {
    var mysteryNumber = Math.random() * 100 + 1;    //Math.random() returns a random floating decimal between 0 and 1. Mult by 100 to get number greater than or equal to 1. Add 1 to avoid zeros
    mysteryNumber  = Math.round(mysteryNumber);          //Rounds up or down the floating point number to nearest integer.

    if(mysteryNumber === 101)   //from Line 8, if number is 100 and 1 is added, 101 results and the range is 1-100
    {
        mysteryNumber = 100;    //correct 101 to 100
    }
    return mysteryNumber;
}//end mysteryNum function

//need computer to make a guess.
function guessNum(){
    var guessNumber = Math.random() * 100 + 1;
    guessNumber = Math.round(guessNumber);
    return guessNumber;
}//end guessNum function

var MN = mysteryNum();
var GN = guessNum();

   console.log("The mystery number is:" + MN);
   console.log("the guess number is: " + GN);

var low = 1;
var high = 100;
var guesses = [];
guesses.push(GN);

function hiLo(MN, GN)
{
    for(var i=0; i < 51; i++) {                           //say MN = 30   GN = 60
        if (GN === MN) {
            console.log("Guess is correct");
            i = 1000;
        }
        else if (GN < MN) {
            console.log("Guess is too low!");
            low = GN;
            GN = Math.round((low + high)/2);
            guesses.push(GN);
            console.log("The new guess number is: " + GN);
            }
        else
            {
                console.log("Guess is too high");
                high = GN;
                GN = Math.round((low+high)/2)
                guesses.push(GN);
                console.log("The new guess number is: " + GN);
            }
        }
}//end hiLo

var highLow = hiLo(MN, GN);
console.log(guesses);












